CREATE TABLE IF NOT EXISTS users (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(55) NOT NULL,
    name VARCHAR(55) NOT NULL,
    surname VARCHAR(55) NOT NULL,
    email VARCHAR(55) NOT NULL,
    password VARCHAR(55) NOT NULL,
    type VARCHAR(55)
);
